//
//  ManualMocks.swift
//  SwiftPhoenixClient
//
//  Created by Daniel Rees on 2/26/19.
//

/// These mock classes are not generated by Sourcery. Ideally they would be
/// but there are some issues with generic types in the stencil templates





//----------------------------------------------------------------------
// MARK: - SocketMock
//----------------------------------------------------------------------

