source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
swift_version = "4.0"

# Pods are noisy, especially the ObjC based ones
inhibit_all_warnings!



target 'ChatExample' do
  use_frameworks!

  pod "SwiftPhoenixClient", :path => "../"
end
