source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftPhoenixClient_Example' do
  pod "SwiftPhoenixClient", :path => "../"
end

target 'SwiftPhoenixClient_Tests' do
  pod "SwiftPhoenixClient", :path => "../"

  
end
